import {test,after,before} from 'node:test';
import assert from 'node:assert/strict';
import {app,preview,validateFiles} from './server.mjs';
before(async()=>{await new Promise(r=>app.listen(3000,'127.0.0.1',r));await new Promise(r=>preview.listen(3001,'127.0.0.1',r));});
after(async()=>{await Promise.all([new Promise(r=>app.close(r)),new Promise(r=>preview.close(r))]);});
test('reject traversal, invalid types, and oversized projects',()=>{for(const files of [{'../index.html':'x'},{'a/../a.js':'x'},{'.env':'secret'},{'a.js':false},{'a.js':'x'.repeat(2000001)},{}])assert.throws(()=>validateFiles(files));assert.doesNotThrow(()=>validateFiles({'pages/a.html':'مرحبا','data.xml':'<a/>'}));});
test('reject cross-origin mutations and unauthenticated publishing',async()=>{let r=await fetch('http://localhost:3000/api/publish',{method:'POST',headers:{Origin:'http://evil.test'},body:'{}'});assert.equal(r.status,403);r=await fetch('http://localhost:3000/api/publish',{method:'POST',headers:{Origin:'http://localhost:3000'},body:'{}'});assert.equal(r.status,401);});
test('preview preserves files and isolates executable content',async()=>{const r=await fetch('http://localhost:3000/api/preview',{method:'POST',headers:{Origin:'http://localhost:3000'},body:JSON.stringify({entry:'index.html',files:{'index.html':'<h1>مرحبا</h1>','data.xml':'<a/>'}})});assert.equal(r.status,200);const p=await r.json(),page=await fetch(p.url);assert.equal(await page.text(),'<h1>مرحبا</h1>');assert.match(page.headers.get('content-security-policy'),/sandbox allow-scripts/);assert.equal(await (await fetch(p.url.replace('index.html','data.xml'))).text(),'<a/>');assert.equal((await fetch(p.url.replace('index.html','missing.js'))).status,404);});
test('invalid OAuth callback fails closed',async()=>{assert.equal((await fetch('http://localhost:3000/auth/callback?state=fake&code=fake')).status,403);const data=await(await fetch('http://localhost:3000/api/me')).json();assert.equal(data.user,null);assert.equal(Object.hasOwn(data,'token'),false);});
